- name: create rhcos tftp directory
  file:
    path: /var/lib/tftpboot/rhcos
    state: directory
    mode: 0755

- name: download rhcos images
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: 0555
  loop:
    - url: "{{ rhcos_images_repo  }}/{{ rhcos_images_initramfs }}"
      dest: /var/lib/tftpboot/rhcos/initramfs.img
    - url: "{{ rhcos_images_repo  }}/{{ rhcos_images_kernel }}"
      dest: /var/lib/tftpboot/rhcos/kernel
    - url: "{{ rhcos_images_repo  }}/{{ rhcos_images_rootfs }}"
      dest: /var/www/html/rootfs.img
    - url: "{{ rhcos_images_repo  }}/{{ rhcos_images_image }}"
      dest: /var/www/html/image.raw.gz
  loop_control:
    label: "{{ item.dest }}"

- name: publish ignition files
  copy:
    src: "{{ item.src }}"
    dest: "/var/www/html/{{ item.dest }}"
    mode: 0555
  loop:
    - src: "{{ rhcos_images_bootstrap_ign }}"
      dest: bootstrap.ign
    - src: "{{ rhcos_images_master_ign }}"
      dest: master.ign
    - src: "{{ rhcos_images_worker_ign }}"
      dest: worker.ign
  loop_control:
    label: "{{ item.dest }}"
