- name: get ilo server power status
  shell: >
    hpilo_cli -l "{{ management_user }}" -p '{{ management_pass }}' -j
    "{{ management_hostname }}" get_host_power_status
  delegate_to: localhost
  become: no
  register: ilo_power_status
  changed_when: no

- name: power off ilo server power state
  shell: >
    hpilo_cli -l "{{ management_user }}" -p '{{ management_pass }}' -y
    "{{ management_hostname }}" hold_pwr_btn
  delegate_to: localhost
  become: no
  when: "ilo_power_status.stdout != '\"OFF\"'"

- name: wait until ilo server powers off
  shell: >
    hpilo_cli -l "{{ management_user }}" -p '{{ management_pass }}' -j
    "{{ management_hostname }}" get_host_power_status
  delegate_to: localhost
  become: no
  register: ilo_power_status_wait
  until: "ilo_power_status_wait.stdout == '\"OFF\"'"
  retries: 25
  changed_when: no
  when: "ilo_power_status.stdout != '\"OFF\"'"
